# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Is visible'),
        ),
    ]
