# Generated by Django 3.0.13 on 2021-05-23 09:00

import clothes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_currency'),
        ('categories', '0009_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', clothes.models.SexField(blank=False, choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], max_length=10, verbose_name='Sex')),
                ('size', models.IntegerField(choices=[(44, '44 (S)'), (46, '46 (M)'), (48, '48 (M)'), (50, '50 (L)'), (52, '52 (XL)'), (54, '54 (XXL)'), (56, '56 (XXL)'), (58, '58 (XXL)'), (60, '60 (XXXL)'), (62, '62 (XXXL)'), (42, '42 (S)'), (44, '44 (M)'), (46, '46 (M)'), (48, '48 (L)'), (50, '50 (XL)'), (52, '52 (XXL)'), (54, '54 (XXL)'), (56, '56 (XXL)'), (58, '58 (XXXL)'), (60, '60 (XXXL)')], verbose_name='Size')),
                ('breast_size', models.IntegerField(blank=True, null=True, verbose_name='Breast size')),
                ('waist_volume', models.IntegerField(blank=True, null=True, verbose_name='Waist volume')),
                ('hips_volume', models.IntegerField(blank=True, null=True, verbose_name='Hips volume')),
                ('sleeve_length', models.IntegerField(blank=True, null=True, verbose_name='Length of the sleeve from the shoulder')),
                ('shoulder_length', models.IntegerField(blank=True, null=True, verbose_name='Shoulder length')),
                ('product_length', models.IntegerField(blank=True, null=True, verbose_name='Product length')),
                ('back_width', models.IntegerField(blank=True, null=True, verbose_name='Back width')),
                ('neck_volume', models.IntegerField(blank=True, null=True, verbose_name='Neck volume')),
                ('length_of_dress_up_to_waist', models.IntegerField(blank=True, null=True, verbose_name='Length of dress up to waist')),
                ('length_of_dress_from_waist', models.IntegerField(blank=True, null=True, verbose_name='Length of dress from waist')),
                ('ordered_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothe_sizes', to='orders.OrderedProduct', verbose_name='Ordered product')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.TextField(blank=True, max_length=4096, verbose_name='Size grid')),
                ('grid_uk', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Size grid')),
                ('grid_ru', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Size grid')),
                ('age', models.CharField(blank=True, choices=[('adult', 'Adult'), ('child', 'Child')], max_length=100, verbose_name='Age')),
                ('sex', clothes.models.SexField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], max_length=10, verbose_name='Sex')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_profile', to='categories.Category', verbose_name='Category')),
            ],
        ),
    ]
