# Generated by Django 3.0.13 on 2021-05-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_mptt'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_name_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product name'),
        ),
    ]
