# Generated by Django 3.0.13 on 2021-05-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_mptt'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='age',
            field=models.CharField(blank=True, choices=[('adult', 'Adult'), ('child', 'Child')], max_length=100, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='category',
            name='grid',
            field=models.TextField(blank=True, max_length=4096, verbose_name='Size grid'),
        ),
        migrations.AddField(
            model_name='category',
            name='grid_ru',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Size grid'),
        ),
        migrations.AddField(
            model_name='category',
            name='grid_uk',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Size grid'),
        ),
        migrations.AddField(
            model_name='category',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], max_length=10, verbose_name='Sex'),
        ),
    ]
