# Generated by Django 3.0.13 on 2021-07-02 15:57

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hash',
            field=models.CharField(default=orders.models._generate_hash, max_length=10),
        ),
    ]
